heurist-network/heurist-agent-framework

.env.example, agents/core_agent.py, config/prompts.yaml, interfaces/twitter_reply.py, platforms/twitter_api.py, test_twitter_monitor.py, utils/__init__.py
=> refactor, wip: twitter reply interface

agents/core_agent.py, config/prompts.yaml, core/config.py, interfaces/twitter_reply.py, main_twitter_reply.py, test_twitter_monitor.py, test_twitter_reply_agent.py, utils/__init__.py, utils/llm_utils.py, utils/text_utils.py
and move PromptConfig to a singleton
=> feat: filter twitter posts, add some util functions

agents/core_agent.py, agents/tool_box.py, agents/tool_decorator_example.py, agents/tools.py, core/embedding.py, core/llm.py, interfaces/telegram.py, interfaces/twitter_post.py, main_console.py
Upgrade to V003 agent framework. Modularized functions, focus on handle_message as augmented llm and addition of COT Flow for core_agent
=> V0.0.3 prototype

core/videogen.py, examples/test_videogen.py
=> feat: integrate video gen api

mesh/duckduckgo_search_agent.py, mesh/tests/duckduckgo_search_agent.py, mesh/tests/duckduckgo_search_agent_example.yaml
This PR adds a new DuckDuckGo Search Agent that fetches and analyzes web search results using AI using the DuckDuckGo API, through the DDGS Library, along with texts and example `yaml` output.
=> feat: add duckduckgo search agent

mesh/coingecko_token_info_agent.py, mesh/requirements.txt, mesh/tests/coingecko_token_info_agent.py, mesh/tests/coingecko_token_info_agent_example.yaml
This PR introduces a new Mesh Agent that integrates with the CoinGecko API to provide cryptocurrency market data and token information through natural language queries. The agent enables:
- Token information retrieval using names or CoinGecko IDs
- Real-time trending cryptocurrency tracking
- Detailed market metrics, price data, and supply information
- Cached responses for improved performance
- Structured data output with natural language explanations
The agent serves as a bridge between our system and CoinGecko's comprehensive crypto data, allowing users to query token information in a conversational manner.
- Implements feature request  (https://github.com/heurist-network/heurist-agent-framework/issues/17)
The implementation includes a comprehensive test suite in …
=> feat: coingecko_token_info_agent

mesh/bitquery_sol_token_info_agent.py, mesh/tests/bitquery_sol_token_info_agent.py, mesh/tests/bitquery_sol_token_info_agent_example.yaml, mesh_api.py, requirements.txt
This PR introduces a new Mesh Agent that integrates with the Bitquery API to provide Solana token trading data and trending token tracking via natural language queries. The agent is designed to:
- **Token Trading Information**: Retrieve detailed trading metrics (in last 1 hour) for a given Solana token using its mint address. This includes price data (open, high, low, close), trading volume, and time-series data in 5-minute intervals.
- **Trending Tokens**: Fetch and present the current top trending tokens ((in last 1 hour)) on the Solana network.
- **LLM Integration**: Generate natural language explanations alongside structured data responses.
- **Caching & Retry**: Optimize performance by caching responses for 5 minutes and incorporating retry mechanisms for API calls to handle …
=> feat: add BitquerySolanaTokenInfoAgent

clients/mesh_client.py, mesh/composable_echo_agent.py, mesh/echo_agent.py, mesh/mesh_agent.py, mesh/tests/zkignite_analyst_agent.py, mesh/zkignite_analyst_agent.py, mesh_api.py, mesh_manager.py, requirements.txt
=> feat: push updates to /mesh_task_update during reasoning steps

mesh/elfa_twitter_intelligence_agent.py, mesh/pumpfun_analysis_agent.py, mesh/tests/elfa_twitter_intelligence_agent.py, mesh/tests/elfa_twitter_intelligence_agent_example.yaml, mesh/tests/pumpfun_analysis_agent.py, mesh/tests/pumpfun_analysis_agent_example.yaml
Integrated Pumpfun APIs and Elfa twitter analysis agent in the current PR
Pumpfun Agent accepts argument parsers
Sample:
pumpfun_analysis_agent.py --query-type all
help='Type of query to run. Options: creation, metrics, holders, buyers, holder_status, top_traders, all')
Pumpfun : https://github.com/heurist-network/heurist-agent-framework/issues/25
Elfa : https://github.com/heurist-network/heurist-agent-framework/issues/22
Script and result file in tests folder
Optimization : Yet to be optimized on scale of other agents and usecase
=> Pumpfun and Elfa API

mesh/dexscreener_token_info_agent.py, mesh/tests/dexscreener_token_info_agent.py, mesh/tests/dexscreener_token_info_agent_example.yaml
Add DexScreener Token Info Agent
Added support for all tool operations:
- search_pairs
- get_specific_pair_info
- get_token_pairs
- get_token_profiles
Tested all tool operations with various inputs:
- Token search queries
- Specific pair lookups
- Token pair listings
- Profile retrievals
=> feat: add dexscreener agent

mesh/coingecko_token_info_agent.py
Improved CoinGeckoTokenInfoAgent's system prompt for more concise and user-focused responses, prioritizing relevant metrics and human-readable number formatting while eliminating verbose data output.
See Issue(https://github.com/heurist-network/heurist-agent-framework/issues/38)
=> chore: improve system prompt for coingecko agent

mesh/pumpfun_analysis_agent.py, mesh/tests/pumpfun_analysis_agent.py, mesh/tests/pumpfun_analysis_agent_example.yaml
https://heuristgroup.slack.com/archives/C08C09CTVMH/p1740727221845349
Pumpfun update for 
first, LLM decides a tool call (can be skipped if a tool is specified)
next, call a tool
finally, respond
Following this exact format
https://github.com/heurist-network/heurist-agent-framework/issues/38#issuecomment-2679330971
Example queries
Recent pump.fun token launches
Top holders of 74SBV4zDXxTRgv1pEMoECskKBkZHc2yGPnc7GYVepump
Top traders of Hjw6bEcHtbHGpQr8onG3izfJY5DJiWdt7uk2BfdSpump
=> Pumpfun update

mesh/metasleuth_sol_token_wallet_cluster_agent.py, mesh/tests/metasleuth_sol_token_wallet_cluster_agent.py, mesh/tests/metasleuth_sol_token_wallet_cluster_agent_example.yaml
This PR adds a new mesh agent that integrates with the MetaSleuth API to analyze Solana token wallet clusters. The agent provides the ability to:
1. Fetch and analyze token wallet clusters for any Solana token
2. Retrieve detailed information about specific wallet clusters
3. Process both direct tool calls and natural language queries related to token wallet distributions
4. Present analysis of holder concentration, wallet clusters, and risk assessment
The implementation includes comprehensive error handling, caching, and retry mechanisms to ensure reliable API interactions.
N/A
- Added test script in `mesh/tests/` that demonstrates both direct tool calls and natural language query handling
- Verified API integration with multiple Solana token addresses and wallet clusters
- Tested error …
=> metasleuth_sol_token_wallet_cluster_agent

mesh/bitquery_solana_token_info_agent.py, mesh/dexscreener_token_info_agent.py, mesh/firecrawl_search_agent.py, mesh/goplus_analysis_agent.py, mesh/tests/all_examples.yaml, mesh/tests/bitquery_sol_token_info_agent.py, mesh/tests/bitquery_sol_token_info_agent_example.yaml, mesh/tests/dexscreener_token_info_agent.py, mesh/tests/dexscreener_token_info_agent_example.yaml, mesh/tests/firecrawl_search_agent.py, mesh/tests/firecrawl_search_agent_example.yaml, mesh/tests/goplus_analysis_agent.py, mesh/tests/goplus_analysis_agent_example.yaml
This push have Simplification for tool calling mode for various agents
- firecrawl
- dexscreener
- goplus
- bitquery
https://heuristgroup.slack.com/archives/C08C09CTVMH/p1742432120749209
=> Simplified tool calling mode for various agents

mesh/aave_agent.py, mesh/allora_price_prediction_agent.py, mesh/bitquery_solana_token_info_agent.py, mesh/carv_onchain_data_agent.py, mesh/coingecko_token_info_agent.py, mesh/duckduckgo_search_agent.py, mesh/elfa_twitter_intelligence_agent.py, mesh/exa_search_agent.py, mesh/funding_rate_agent.py, mesh/masa_twitter_search_agent.py, mesh/metasleuth_sol_token_wallet_cluster_agent.py, mesh/pumpfun_token_agent.py, mesh/sol_wallet_agent.py, mesh/tests/aave_agent_example.yaml, mesh/tests/allora_price_prediction_agent_example.yaml, mesh/tests/carv_onchain_data_agent_example.yaml, mesh/tests/coingecko_token_info_agent_example.yaml, mesh/tests/duckduckgo_search_agent_example.yaml, mesh/tests/funding_rate_agent_example.yaml, mesh/tests/masa_twitter_intellgence_agent.py, mesh/tests/masa_twitter_intellgence_agent_example.yaml, mesh/tests/metasleuth_sol_token_wallet_cluster_agent_example.yaml, mesh/tests/twitter_insight_agent.py, mesh/twitter_insight_agent.py
This pull request have tool calling simplification 
- if query is present, it means "agent mode", we use LLM to interpret the query and call tools
- if raw_data_only is present, we return tool results without another LLM call
- if tool is present, it means "direct tool call mode", we typically just proxy the request to 3rd party (plus some data transformation to make it more readable, or shorter)
https://heuristgroup.slack.com/archives/C08C09CTVMH/p1742432120749209
=> update tool call simplification for mesh agents

mesh/agents/dexscreener_token_info_agent.py
update dexscreener agent author info
=> update dexscreener_token_info_agent author info

README.md
Hi! I Fixed agent file paths in README.md to match current project structure.
• Updated all agent paths from `mesh/agent_name.py` to `mesh/agents/agent_name.py` (9 agents total)
=> Update broken links in `README.md`

mesh/agents/twitter_info_agent.py, mesh/tests/twitter_info_agent.py, mesh/tests/twitter_info_agent_example.yaml
Rename TwitterProfileAgent to TwitterInfoAgent and add (1) get twitter details by tweet id (1) general search functionality
This PR renames the existing TwitterProfileAgent to TwitterInfoAgent and expands its functionality by adding a general search tool. Key changes include:
- Renamed class from TwitterProfileAgent to TwitterInfoAgent
- Added new API function `get_twitter_detail` to fetch detailed information about specific tweets, including replies and thread content
- Added new API function `get_general_search` to search for tweets using query terms
- Added helper methods and endpoints for the new functionality
- Updated all related files to reflect the name change
The new functionality has been tested with example API requests to ensure proper parsing of parameters, correct endpoint …
=> Feat/Rename TwitterProfileAgent -> TwitterInfoAgent

mesh/agents/aave_agent.py, mesh/agents/aixbt_project_info_agent.py, mesh/agents/allora_price_prediction_agent.py, mesh/agents/bitquery_solana_token_info_agent.py, mesh/agents/carv_onchain_data_agent.py, mesh/agents/coingecko_token_info_agent.py, mesh/agents/cookie_project_info_agent.py, mesh/agents/deep_research_agent.py, mesh/agents/dexscreener_token_info_agent.py, mesh/agents/duckduckgo_search_agent.py, mesh/agents/elfa_twitter_intelligence_agent.py, mesh/agents/exa_search_agent.py, mesh/agents/firecrawl_search_agent.py, mesh/agents/funding_rate_agent.py, mesh/agents/goplus_analysis_agent.py, mesh/agents/masa_twitter_search_agent.py, mesh/agents/metasleuth_sol_token_wallet_cluster_agent.py, mesh/agents/mindai_kol_agent.py, mesh/agents/moni_twitter_insight_agent.py, mesh/agents/pond_wallet_analysis_agent.py, mesh/agents/pumpfun_token_agent.py, mesh/agents/sol_wallet_agent.py, mesh/agents/space_and_time_agent.py, mesh/agents/tokenmetrics_agent.py, mesh/agents/truth_social_agent.py, mesh/agents/twitter_info_agent.py, mesh/agents/unifai_token_analysis_agent.py, mesh/agents/unifai_web3_news_agent.py, mesh/mesh_agent.py
Fixes issues caused by introducing new `session_context` param in https://github.com/heurist-network/heurist-agent-framework/commit/3965b62bd8b157f637f2152aed71a2d9606e41a2
=> fix: update `_handle_tool_logic` signature

mesh/agents/lets_bonk_token_info_agent.py, mesh/tests/lets_bonk_token_info_agent.py, mesh/tests/lets_bonk_token_info_agent_example.yaml
Add LetsBonk Token Info Agent for Solana Token Analysis
This PR introduces a new specialized agent for analyzing **LetsBonk.fun** tokens on Solana using the Bitquery API. LetsBonk.fun is a token launchpad similar to Pump.fun where tokens "graduate" when they reach certain market cap thresholds.
- **🎓 Graduation Tracking**: Monitor tokens approaching the graduation threshold (~206.9M base tokens) on LetsBonk.fun
- **📊 Trading Analysis**: Track recent trades for specific tokens on Raydium Launchpad  
- **💰 Price Monitoring**: Get real-time price information for LetsBonk.fun tokens
- **🐋 Buyer Analysis**: Identify top buyers and their trading volumes for whale/smart money tracking
- Adds `LetsBonkTokenInfoAgent` class with **4 main tools** for comprehensive token analysis
- Implements …
=> Lets Bonk Agent

mesh/agents/arkham_intelligence_agent.py, mesh/tests/arkham_intelligence_agent.py, mesh/tests/arkham_intelligence_agent_results.yaml
remove _process_token_holders_response
and kept the response flow in existing function only
=> fix: minor patch for token holder

mesh/agents/exa_search_agent.py, mesh/agents/firecrawl_search_agent.py, mesh/agents/firecrawl_search_digest_agent.py, mesh/mesh_agent.py
Add agent‑level timeout/fallback (Firecrawl→Exa)
=> feat: add custom timeouts and fallbacks per agent

CLAUDE.md, mesh/agents/coingecko_token_info_agent.py, mesh/agents/elfa_twitter_intelligence_agent.py, mesh/agents/pumpfun_token_agent.py, mesh/agents/token_resolver_agent.py, mesh/agents/trending_token_agent.py, mesh/agents/unifai_token_analysis_agent.py, mesh/mesh_agent.py, mesh/test_scripts/test_raw_api_responses.py, mesh/test_scripts/test_token_resolver.py, mesh/test_scripts/test_trending_token.py
`_has_useful_data` might be sloppy, but keep it to move faster
=> feat: trending_token_agent and add ad-hoc test scripts
